infare:
  input.url: https://infare-dev-external-dpcandidate.s3.amazonaws.com/hive_csv_altus_gz/part-00000.gz

output:
  directory: /tmp/infare/prices

schema:
  path: cql/prices.cql

cassandra:
  keyspace: infare
  table: prices
  hosts: localhost
  port: 9042
  replication.factor: 1
