case class TripWithConvertedPrice(week: Integer,
                                  weeksBefore: Integer,
                                  carrier: Integer,
                                  bookingClass: java.lang.String,
                                  bookingSite: Integer,
                                  isOneWay: java.lang.Boolean,
                                  origin: Integer,
                                  destination: Integer,
                                  outboundDepartureDate: Integer,
                                  outboundDepartureTime: Integer,
                                  outboundSectorCount: Integer,
                                  id: Integer,
                                  convertedPrice: java.math.BigDecimal)